version: "3.8"
services:
  wxchat:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../data:/app/data # 数据库文件持久化
      - ../uploads:/app/uploads # 文件上传目录
    env_file:
      - .env # 从.env文件加载环境变量
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:3000/login.html",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
